env: local

jwt:
  secret: ufahacksecret
  ttl: 30m

server:
  address: localhost
  port: 8080
  timeout: 30m
  idle_timeout: 30m

database:
  host: localhost
  port: 5432
  name: ufahack
  user: ufahack
  password: ufahacksecret
