// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "ufahack_2023/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserLoginer is an autogenerated mock type for the UserLoginer type
type UserLoginer struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *UserLoginer) Login(ctx context.Context, username string, password string) (*domain.User, string, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewUserLoginer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserLoginer creates a new instance of UserLoginer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserLoginer(t mockConstructorTestingTNewUserLoginer) *UserLoginer {
	mock := &UserLoginer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
